# syntax=docker/dockerfile:1

# ==============================================================================
# STAGE 1: Build hbbs and hbbr in Rust
# ==============================================================================
FROM rust:1.97-alpine AS rust-builder

RUN apk add --no-cache musl-dev gcc pkgconfig libsodium-dev cmake make g++ git sqlite

WORKDIR /usr/src/rustdesk-server
COPY ./rustdesk-server .

ENV DATABASE_URL=sqlite://./db_v2.sqlite3
RUN sqlite3 db_v2.sqlite3 " \
    create table if not exists peer ( \
        guid blob primary key not null, \
        id varchar(100) not null, \
        uuid blob not null, \
        pk blob not null, \
        created_at datetime not null default(current_timestamp), \
        user blob, \
        status tinyint, \
        note varchar(300), \
        info text not null \
    ) without rowid; \
    create unique index if not exists index_peer_id on peer (id); \
    create index if not exists index_peer_user on peer (user); \
    create index if not exists index_peer_created_at on peer (created_at); \
    create index if not exists index_peer_status on peer (status); \
"

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/src/rustdesk-server/target \
    cargo build --release && \
    mkdir -p /usr/src/rustdesk-server/bin && \
    cp target/release/hbbs /usr/src/rustdesk-server/bin/hbbs && \
    cp target/release/hbbr /usr/src/rustdesk-server/bin/hbbr

# ==============================================================================
# STAGE 2: Final Production Image
# ==============================================================================
FROM alpine:3.21
WORKDIR /root

RUN apk add --no-cache libsodium ca-certificates

COPY --from=rust-builder /usr/src/rustdesk-server/bin/hbbs /usr/bin/hbbs
COPY --from=rust-builder /usr/src/rustdesk-server/bin/hbbr /usr/bin/hbbr

EXPOSE 21115 21116 21116/udp 21117 21118 21119

CMD ["hbbs"]
