# ------------------------------------------------------------------------------
# RustDesk Nginx & Container Log Rotation Config
# ------------------------------------------------------------------------------

# 1. Nginx Access & Error Logs (Mounted in ./data/logs/nginx)
./data/logs/nginx/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 101 101
    sharedscripts
    postrotate
        docker exec rustdesk-proxy nginx -s reload >/dev/null 2>&1 || true
    endscript
}
